### ISSUE TITLE
crash if nether jungle is disabled 

### ISSUE THREAD

**Issue by modpackmaker999** [jbredwards/Nether-API#8]
when you have Nether API with Betternether installed If you try to disable the nether jungle it crashes here is the crash report or log.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Nether API Plugin (Nether-API-v1.3.0-mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 10/5/24 1:33 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at git.jbredwards.nether_api.mod.common.compat.betternether.BiomeBetterNether.<init>(BiomeBetterNether.java:41)
	at git.jbredwards.nether_api.mod.common.compat.betternether.BetterNetherHandler.lambda$registerBiomes$1(BetterNetherHandler.java:78)
	at git.jbredwards.nether_api.mod.common.compat.betternether.BetterNetherHandler.registerBiomes(BetterNetherHandler.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_BetterNetherHandler_registerBiomes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at git.jbredwards.nether_api.mod.common.compat.betternether.BiomeBetterNether.<init>(BiomeBetterNether.java:41)
	at git.jbredwards.nether_api.mod.common.compat.betternether.BetterNetherHandler.lambda$registerBiomes$1(BetterNetherHandler.java:78)
	at git.jbredwards.nether_api.mod.common.compat.betternether.BetterNetherHandler.registerBiomes(BetterNetherHandler.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_BetterNetherHandler_registerBiomes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_422, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 663322320 bytes (632 MB) / 850395136 bytes (811 MB) up to 7456948224 bytes (7111 MB)
	JVM Flags: 1 total; -Xmx8000M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID           | Version      | Source                         | Signature                                |
	|:----- |:------------ |:------------ |:------------------------------ |:---------------------------------------- |
	| LCH   | minecraft    | 1.12.2       | minecraft.jar                  | None                                     |
	| LCH   | mcp          | 9.42         | minecraft.jar                  | None                                     |
	| LCH   | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge        | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | betternether | 0.1.8.6      | betternether-0.1.8.6 (2).jar   | None                                     |
	| LCH   | stygian      | 1.0.4        | stygian-1.0.4 (2).jar          | None                                     |
	| LCH   | nether_api   | 1.3.0        | Nether-API-v1.3.0-mc1.12.2.jar | None                                     |

	Loaded coremods (and transformers): 
Nether API Plugin (Nether-API-v1.3.0-mc1.12.2.jar)
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerBetterNetherConfigLoader
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerBetterNetherFirefly
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerBetterNetherGenerator
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerBiomesOPlentyBiomes
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerBiomesOPlentyDecorator
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerBiomesOPlentyFixes
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerJITLCascadingFix
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerJITLGenerator
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerJITLTowerFix
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerLibraryExCascadingFix
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerNethercraftEvents
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerNetherEXBiomes
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerNetherExOverride
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerStygianEndBiomes
  git.jbredwards.nether_api.mod.asm.transformers.modded.TransformerStygianEndCascadingFix
  git.jbredwards.nether_api.mod.asm.transformers.modded.height.Transformer_NetherHeight_BiomesOPlenty
  git.jbredwards.nether_api.mod.asm.transformers.modded.height.Transformer_NetherHeight_Natura
  git.jbredwards.nether_api.mod.asm.transformers.modded.height.Transformer_NetherHeight_NetherEx
  git.jbredwards.nether_api.mod.asm.transformers.vanilla.Transformer_MC_10369
  git.jbredwards.nether_api.mod.asm.transformers.vanilla.TransformerBiomeEndDecorator
  git.jbredwards.nether_api.mod.asm.transformers.vanilla.TransformerBiomeHell
  git.jbredwards.nether_api.mod.asm.transformers.vanilla.TransformerCommandLocate
  git.jbredwards.nether_api.mod.asm.transformers.vanilla.TransformerDragonSpawnManager
  git.jbredwards.nether_api.mod.asm.transformers.vanilla.TransformerEntityRenderer
  git.jbredwards.nether_api.mod.asm.transformers.vanilla.TransformerMapGenCavesHell
  git.jbredwards.nether_api.mod.asm.transformers.vanilla.TransformerMapGenEndCity
  git.jbredwards.nether_api.mod.asm.transformers.vanilla.TransformerWorldClient
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 24.3.1.240216' Renderer: 'Radeon RX 570 Series'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: Radeon RX 570 Series GL version 4.6.0 Compatibility Profile Context 24.3.1.240216, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz

**Comment by jbredwards** [comment]
Fixed in v1.4.0!
